on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: Check SSH connectivity
        run: |
          echo "Testing SSH connection..."
          ssh -v -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} \
          -i <(echo "${{ secrets.SSH_PRIVATE_KEY }}") \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'"
        
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.WORK_DIR }}  
            git pull
